### ISSUE TITLE
Quote list does not show the new inserted data

### ISSUE THREAD

**Issue by harysuryanto** [harysuryanto/react-quotes#1]
When I add new data and click the Save button, the new data does not show in the list (list is not updated when new data is added). But when I do other actions, like clicking Add Quotes and delete buttons, the list gets updated. Basically the list will only update if I do any action that trigger the `useEffect()` method in `QuoteList.js`.

**Comment by fajarsj** [comment]
Hi @harysuryanto, I think I understand your issue, and after I investigate the issue is coming from `App.js` in `insertQuote` function where you actually reference the original value, `const temp_quotes = quotes;` which is a bad practice always remember NOT to mutate the original array, but instead do this `const temp_quotes = [...quotes];`, after that, still on `App.js` add this 

```
useEffect(() => {
  console.log('App.js rerenderd');
}, [quotes]); << add this
```
This means, every time states of quotes changed, rerender the component.

I hope this helps, great progress too, keep it up! I wish I can see more 😃.

**Comment by harysuryanto** [comment]
Your solution worked! Thanks! I appreciate it. As you suggested, the problem was fixed by doing `const temp_quotes = [...quotes];`. I didn't know there such rule in assigning an array. 😂😂
